services:
  app:
    build: docker
    command: python manage.py runserver
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${HTTP_PORT}:8000"
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: mariadb:latest
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  adminer:
    image: adminer:latest
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - app_network
    depends_on:
      - db

volumes:
  db_data:

networks:
  app_network: